import Head from 'next/head'
import Feed from '../Components/Feed'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Reels Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Feed/>
      </div>
    </div>
  )
}
